name: Test
on: [pull_request]
jobs:
  lint-build:
    name: "Lint & Build"
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v2
      # install node
      - name: Use Node.js 16.10.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.10.0
      # lint, build, test
      - run: npm install
      - run: npm run test:karma
      - run: npm run test:coverage
      - run: npm run lint
      - name: Codecov
        uses: codecov/codecov-action@v1
